### ISSUE TITLE
syntax highlight with newline

### ISSUE THREAD

**Issue by marcelhollerbach** [SublimeText/AAAPackageDev#64]
I have the following code:

```

 comment: general eolian class
  begin: (class|mixin|interface|abstract) ([A-Za-z0-9._]+)[ \n]*[\(]*[[A-Za-z0-9._]+, \n]+[\)]*[ \n]*\{
  beginCaptures:
      '1': {name: "keyword.other"}
  end: \}
  patterns:
  - include: '#methods_block'
  - include: '#implements'
  - include: '#events'
  - include: '#comments'

```
I can enter as many " " as I want, but no newline between class(..) and {
Is the rule wrong here ? or is this a bug?
